# Generated by Django 6.0 on 2025-12-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
